//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Лаб3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Triangle
    {
        public int ID { get; set; }
        public Nullable<double> Length_A { get; set; }
        public Nullable<double> Length_B { get; set; }
        public Nullable<double> Length_C { get; set; }
        public string Type_Triangle { get; set; }
        public string Error { get; set; }
    }
}
